export const RECIPES = [
	{ label: 'Cover', value: 'Cover' },
	{ label: 'Remix', value: 'Remix' },
	{ label: 'Mash-up', value: 'Mash-up' },
  { label: 'Self Cover', value: 'Self Cover' },
  { label: 'Instrumental Cover', value: 'Instrumental Cover' },
];

// https://gist.github.com/sampsyo
export const FLAVOURS = [
{'label':'Any style !','value':'Any style !'},
{'label':'2 tone','value':'2 tone'},
{'label':'2-step garage','value':'2-step garage'},
{'label':'4-beat','value':'4-beat'},
{'label':'4x4 garage','value':'4x4 garage'},
{'label':'8-bit','value':'8-bit'},
{'label':'acapella','value':'acapella'},
{'label':'acid','value':'acid'},
{'label':'acid breaks','value':'acid breaks'},
{'label':'acid house','value':'acid house'},
{'label':'acid jazz','value':'acid jazz'},
{'label':'acid rock','value':'acid rock'},
{'label':'acoustic music','value':'acoustic music'},
{'label':'acousticana','value':'acousticana'},
{'label':'adult contemporary music','value':'adult contemporary music'},
{'label':'african popular music','value':'african popular music'},
{'label':'african rumba','value':'african rumba'},
{'label':'afrobeat','value':'afrobeat'},
{'label':'aleatoric music','value':'aleatoric music'},
{'label':'alternative country','value':'alternative country'},
{'label':'alternative dance','value':'alternative dance'},
{'label':'alternative hip hop','value':'alternative hip hop'},
{'label':'alternative metal','value':'alternative metal'},
{'label':'alternative rock','value':'alternative rock'},
{'label':'ambient','value':'ambient'},
{'label':'ambient house','value':'ambient house'},
{'label':'ambient music','value':'ambient music'},
{'label':'americana','value':'americana'},
{'label':'anarcho punk','value':'anarcho punk'},
{'label':'anime music','value':'anime music'},
{'label':'anti-folk','value':'anti-folk'},
{'label':'apala','value':'apala'},
{'label':'ape haters','value':'ape haters'},
{'label':'arab pop','value':'arab pop'},
{'label':'arabesque','value':'arabesque'},
{'label':'arabic pop','value':'arabic pop'},
{'label':'argentine rock','value':'argentine rock'},
{'label':'ars antiqua','value':'ars antiqua'},
{'label':'ars nova','value':'ars nova'},
{'label':'art punk','value':'art punk'},
{'label':'art rock','value':'art rock'},
{'label':'ashiq','value':'ashiq'},
{'label':'asian american jazz','value':'asian american jazz'},
{'label':'australian country music','value':'australian country music'},
{'label':'australian hip hop','value':'australian hip hop'},
{'label':'australian pub rock','value':'australian pub rock'},
{'label':'austropop','value':'austropop'},
{'label':'avant-garde','value':'avant-garde'},
{'label':'avant-garde jazz','value':'avant-garde jazz'},
{'label':'avant-garde metal','value':'avant-garde metal'},
{'label':'avant-garde music','value':'avant-garde music'},
{'label':'axé','value':'axé'},
{'label':'bac-bal','value':'bac-bal'},
{'label':'bachata','value':'bachata'},
{'label':'background music','value':'background music'},
{'label':'baggy','value':'baggy'},
{'label':'baila','value':'baila'},
{'label':'baile funk','value':'baile funk'},
{'label':'baisha xiyue','value':'baisha xiyue'},
{'label':'baithak gana','value':'baithak gana'},
{'label':'baião','value':'baião'},
{'label':'bajourou','value':'bajourou'},
{'label':'bakersfield sound','value':'bakersfield sound'},
{'label':'bakou','value':'bakou'},
{'label':'bakshy','value':'bakshy'},
{'label':'bal-musette','value':'bal-musette'},
{'label':'balakadri','value':'balakadri'},
{'label':'balinese gamelan','value':'balinese gamelan'},
{'label':'balkan pop','value':'balkan pop'},
{'label':'ballad','value':'ballad'},
{'label':'ballata','value':'ballata'},
{'label':'ballet','value':'ballet'},
{'label':'bamboo band','value':'bamboo band'},
{'label':'bambuco','value':'bambuco'},
{'label':'banda','value':'banda'},
{'label':'bangsawan','value':'bangsawan'},
{'label':'bantowbol','value':'bantowbol'},
{'label':'barbershop music','value':'barbershop music'},
{'label':'barndance','value':'barndance'},
{'label':'baroque music','value':'baroque music'},
{'label':'baroque pop','value':'baroque pop'},
{'label':'bass music','value':'bass music'},
{'label':'batcave','value':'batcave'},
{'label':'batucada','value':'batucada'},
{'label':'batuco','value':'batuco'},
{'label':'batá-rumba','value':'batá-rumba'},
{'label':'beach music','value':'beach music'},
{'label':'beat','value':'beat'},
{'label':'beatboxing','value':'beatboxing'},
{'label':'beautiful music','value':'beautiful music'},
{'label':'bebop','value':'bebop'},
{'label':'beiguan','value':'beiguan'},
{'label':'bel canto','value':'bel canto'},
{'label':'bend-skin','value':'bend-skin'},
{'label':'benga','value':'benga'},
{'label':'berlin school of electronic music','value':'berlin school of electronic music'},
{'label':'bhajan','value':'bhajan'},
{'label':'bhangra','value':'bhangra'},
{'label':'bhangra-wine','value':'bhangra-wine'},
{'label':'bhangragga','value':'bhangragga'},
{'label':'bhangramuffin','value':'bhangramuffin'},
{'label':'big band','value':'big band'},
{'label':'big band music','value':'big band music'},
{'label':'big beat','value':'big beat'},
{'label':'biguine','value':'biguine'},
{'label':'bihu','value':'bihu'},
{'label':'bikutsi','value':'bikutsi'},
{'label':'biomusic','value':'biomusic'},
{'label':'bitcore','value':'bitcore'},
{'label':'bitpop','value':'bitpop'},
{'label':'black metal','value':'black metal'},
{'label':'blackened death metal','value':'blackened death metal'},
{'label':'blue-eyed soul','value':'blue-eyed soul'},
{'label':'bluegrass','value':'bluegrass'},
{'label':'blues','value':'blues'},
{'label':'blues ballad','value':'blues ballad'},
{'label':'blues-rock','value':'blues-rock'},
{'label':'boogie','value':'boogie'},
{'label':'boogie woogie','value':'boogie woogie'},
{'label':'boogie-woogie','value':'boogie-woogie'},
{'label':'bossa nova','value':'bossa nova'},
{'label':'brass band','value':'brass band'},
{'label':'brazilian funk','value':'brazilian funk'},
{'label':'brazilian jazz','value':'brazilian jazz'},
{'label':'breakbeat','value':'breakbeat'},
{'label':'breakbeat hardcore','value':'breakbeat hardcore'},
{'label':'breakcore','value':'breakcore'},
{'label':'breton music','value':'breton music'},
{'label':'brill building pop','value':'brill building pop'},
{'label':'britfunk','value':'britfunk'},
{'label':'british blues','value':'british blues'},
{'label':'british invasion','value':'british invasion'},
{'label':'britpop','value':'britpop'},
{'label':'broken beat','value':'broken beat'},
{'label':'brown-eyed soul','value':'brown-eyed soul'},
{'label':'brukdown','value':'brukdown'},
{'label':'brutal death metal','value':'brutal death metal'},
{'label':'bubblegum dance','value':'bubblegum dance'},
{'label':'bubblegum pop','value':'bubblegum pop'},
{'label':'bulerias','value':'bulerias'},
{'label':'bumba-meu-boi','value':'bumba-meu-boi'},
{'label':'bunraku','value':'bunraku'},
{'label':'burger-highlife','value':'burger-highlife'},
{'label':'burgundian school','value':'burgundian school'},
{'label':'byzantine chant','value':'byzantine chant'},
{'label':'ca din tulnic','value':'ca din tulnic'},
{'label':'ca pe lunca','value':'ca pe lunca'},
{'label':'ca trù','value':'ca trù'},
{'label':'cabaret','value':'cabaret'},
{'label':'cadence','value':'cadence'},
{'label':'cadence rampa','value':'cadence rampa'},
{'label':'cadence-lypso','value':'cadence-lypso'},
{'label':'café-aman','value':'café-aman'},
{'label':'cai luong','value':'cai luong'},
{'label':'cajun music','value':'cajun music'},
{'label':'cakewalk','value':'cakewalk'},
{'label':'calenda','value':'calenda'},
{'label':'calentanos','value':'calentanos'},
{'label':'calgia','value':'calgia'},
{'label':'calypso','value':'calypso'},
{'label':'calypso jazz','value':'calypso jazz'},
{'label':'calypso-style baila','value':'calypso-style baila'},
{'label':'campursari','value':'campursari'},
{'label':'canatronic','value':'canatronic'},
{'label':'candombe','value':'candombe'},
{'label':'canon','value':'canon'},
{'label':'canrock','value':'canrock'},
{'label':'cantata','value':'cantata'},
{'label':'cante chico','value':'cante chico'},
{'label':'cante jondo','value':'cante jondo'},
{'label':'canterbury scene','value':'canterbury scene'},
{'label':'cantiga','value':'cantiga'},
{'label':'cantique','value':'cantique'},
{'label':'cantiñas','value':'cantiñas'},
{'label':'canto livre','value':'canto livre'},
{'label':'canto nuevo','value':'canto nuevo'},
{'label':'canto popular','value':'canto popular'},
{'label':'cantopop','value':'cantopop'},
{'label':'canzone napoletana','value':'canzone napoletana'},
{'label':'cape jazz','value':'cape jazz'},
{'label':'capoeira music','value':'capoeira music'},
{'label':'caracoles','value':'caracoles'},
{'label':'carceleras','value':'carceleras'},
{'label':'cardas','value':'cardas'},
{'label':'cardiowave','value':'cardiowave'},
{'label':'carimbó','value':'carimbó'},
{'label':'cariso','value':'cariso'},
{'label':'carnatic music','value':'carnatic music'},
{'label':'carol','value':'carol'},
{'label':'cartageneras','value':'cartageneras'},
{'label':'cassette culture','value':'cassette culture'},
{'label':'casséy-co','value':'casséy-co'},
{'label':'cavacha','value':'cavacha'},
{'label':'caveman','value':'caveman'},
{'label':'caña','value':'caña'},
{'label':'celempungan','value':'celempungan'},
{'label':'cello rock','value':'cello rock'},
{'label':'celtic','value':'celtic'},
{'label':'celtic fusion','value':'celtic fusion'},
{'label':'celtic metal','value':'celtic metal'},
{'label':'celtic punk','value':'celtic punk'},
{'label':'celtic reggae','value':'celtic reggae'},
{'label':'celtic rock','value':'celtic rock'},
{'label':'cha-cha-cha','value':'cha-cha-cha'},
{'label':'chakacha','value':'chakacha'},
{'label':'chalga','value':'chalga'},
{'label':'chamamé','value':'chamamé'},
{'label':'chamber jazz','value':'chamber jazz'},
{'label':'chamber music','value':'chamber music'},
{'label':'chamber pop','value':'chamber pop'},
{'label':'champeta','value':'champeta'},
{'label':'changuí','value':'changuí'},
{'label':'chanson','value':'chanson'},
{'label':'chant','value':'chant'},
{'label':'charanga','value':'charanga'},
{'label':'charanga-vallenata','value':'charanga-vallenata'},
{'label':'charikawi','value':'charikawi'},
{'label':'chastushki','value':'chastushki'},
{'label':'chau van','value':'chau van'},
{'label':'chemical breaks','value':'chemical breaks'},
{'label':'chicago blues','value':'chicago blues'},
{'label':'chicago house','value':'chicago house'},
{'label':'chicago soul','value':'chicago soul'},
{'label':'chicano rap','value':'chicano rap'},
{'label':'chicha','value':'chicha'},
{'label':'chicken scratch','value':'chicken scratch'},
{'label':'children\'s music','value':'children\'s music'},
{'label':'chillout','value':'chillout'},
{'label':'chillwave','value':'chillwave'},
{'label':'chimurenga','value':'chimurenga'},
{'label':'chinese music','value':'chinese music'},
{'label':'chinese pop','value':'chinese pop'},
{'label':'chinese rock','value':'chinese rock'},
{'label':'chip music','value':'chip music'},
{'label':'cho-kantrum','value':'cho-kantrum'},
{'label':'chongak','value':'chongak'},
{'label':'chopera','value':'chopera'},
{'label':'chorinho','value':'chorinho'},
{'label':'choro','value':'choro'},
{'label':'chouval bwa','value':'chouval bwa'},
{'label':'chowtal','value':'chowtal'},
{'label':'christian alternative','value':'christian alternative'},
{'label':'christian black metal','value':'christian black metal'},
{'label':'christian electronic music','value':'christian electronic music'},
{'label':'christian hardcore','value':'christian hardcore'},
{'label':'christian hip hop','value':'christian hip hop'},
{'label':'christian industrial','value':'christian industrial'},
{'label':'christian metal','value':'christian metal'},
{'label':'christian music','value':'christian music'},
{'label':'christian punk','value':'christian punk'},
{'label':'christian r&b','value':'christian r&b'},
{'label':'christian rock','value':'christian rock'},
{'label':'christian ska','value':'christian ska'},
{'label':'christmas carol','value':'christmas carol'},
{'label':'christmas music','value':'christmas music'},
{'label':'chumba','value':'chumba'},
{'label':'chut-kai-pang','value':'chut-kai-pang'},
{'label':'chutney','value':'chutney'},
{'label':'chutney soca','value':'chutney soca'},
{'label':'chutney-bhangra','value':'chutney-bhangra'},
{'label':'chutney-hip hop','value':'chutney-hip hop'},
{'label':'chutney-soca','value':'chutney-soca'},
{'label':'chylandyk','value':'chylandyk'},
{'label':'chzalni','value':'chzalni'},
{'label':'chèo','value':'chèo'},
{'label':'cigányzene','value':'cigányzene'},
{'label':'classic','value':'classic'},
{'label':'classic country','value':'classic country'},
{'label':'classic female blues','value':'classic female blues'},
{'label':'classic rock','value':'classic rock'},
{'label':'classical music','value':'classical music'},
{'label':'classical music era','value':'classical music era'},
{'label':'clicks n cuts','value':'clicks n cuts'},
{'label':'close harmony','value':'close harmony'},
{'label':'club music','value':'club music'},
{'label':'cocobale','value':'cocobale'},
{'label':'coimbra fado','value':'coimbra fado'},
{'label':'coladeira','value':'coladeira'},
{'label':'colombianas','value':'colombianas'},
{'label':'combined rhythm','value':'combined rhythm'},
{'label':'comedy rap','value':'comedy rap'},
{'label':'comedy rock','value':'comedy rock'},
{'label':'comic opera','value':'comic opera'},
{'label':'comparsa','value':'comparsa'},
{'label':'compas direct','value':'compas direct'},
{'label':'compas meringue','value':'compas meringue'},
{'label':'concert overture','value':'concert overture'},
{'label':'concerto','value':'concerto'},
{'label':'concerto grosso','value':'concerto grosso'},
{'label':'congo','value':'congo'},
{'label':'conjunto','value':'conjunto'},
{'label':'contemporary christian','value':'contemporary christian'},
{'label':'contemporary christian music','value':'contemporary christian music'},
{'label':'contemporary r&b','value':'contemporary r&b'},
{'label':'contonbley','value':'contonbley'},
{'label':'contradanza','value':'contradanza'},
{'label':'cool jazz','value':'cool jazz'},
{'label':'corrido','value':'corrido'},
{'label':'corsican polyphonic song','value':'corsican polyphonic song'},
{'label':'cothoza mfana','value':'cothoza mfana'},
{'label':'country','value':'country'},
{'label':'country blues','value':'country blues'},
{'label':'country gospel','value':'country gospel'},
{'label':'country music','value':'country music'},
{'label':'country pop','value':'country pop'},
{'label':'country r&b','value':'country r&b'},
{'label':'country rock','value':'country rock'},
{'label':'country-rap','value':'country-rap'},
{'label':'countrypolitan','value':'countrypolitan'},
{'label':'couple de sonneurs','value':'couple de sonneurs'},
{'label':'coupé-décalé','value':'coupé-décalé'},
{'label':'cowpunk','value':'cowpunk'},
{'label':'cretan music','value':'cretan music'},
{'label':'crossover jazz','value':'crossover jazz'},
{'label':'crossover music','value':'crossover music'},
{'label':'crossover thrash','value':'crossover thrash'},
{'label':'crossover thrash metal','value':'crossover thrash metal'},
{'label':'crunk','value':'crunk'},
{'label':'crunk&b','value':'crunk&b'},
{'label':'crunkcore','value':'crunkcore'},
{'label':'crust punk','value':'crust punk'},
{'label':'csárdás','value':'csárdás'},
{'label':'cuarteto','value':'cuarteto'},
{'label':'cuban rumba','value':'cuban rumba'},
{'label':'cuddlecore','value':'cuddlecore'},
{'label':'cueca','value':'cueca'},
{'label':'cumbia','value':'cumbia'},
{'label':'cumbia villera','value':'cumbia villera'},
{'label':'cybergrind','value':'cybergrind'},
{'label':'dabka','value':'dabka'},
{'label':'dadra','value':'dadra'},
{'label':'daina','value':'daina'},
{'label':'dalauna','value':'dalauna'},
{'label':'dance','value':'dance'},
{'label':'dance music','value':'dance music'},
{'label':'dance-pop','value':'dance-pop'},
{'label':'dance-punk','value':'dance-punk'},
{'label':'dance-rock','value':'dance-rock'},
{'label':'dancehall','value':'dancehall'},
{'label':'dangdut','value':'dangdut'},
{'label':'danger music','value':'danger music'},
{'label':'dansband','value':'dansband'},
{'label':'danza','value':'danza'},
{'label':'danzón','value':'danzón'},
{'label':'dark ambient','value':'dark ambient'},
{'label':'dark cabaret','value':'dark cabaret'},
{'label':'dark pop','value':'dark pop'},
{'label':'darkcore','value':'darkcore'},
{'label':'darkstep','value':'darkstep'},
{'label':'darkwave','value':'darkwave'},
{'label':'de ascultat la servici','value':'de ascultat la servici'},
{'label':'de codru','value':'de codru'},
{'label':'de dragoste','value':'de dragoste'},
{'label':'de jale','value':'de jale'},
{'label':'de pahar','value':'de pahar'},
{'label':'death industrial','value':'death industrial'},
{'label':'death metal','value':'death metal'},
{'label':'death rock','value':'death rock'},
{'label':'death/doom','value':'death/doom'},
{'label':'deathcore','value':'deathcore'},
{'label':'deathgrind','value':'deathgrind'},
{'label':'deathrock','value':'deathrock'},
{'label':'deep funk','value':'deep funk'},
{'label':'deep house','value':'deep house'},
{'label':'deep soul','value':'deep soul'},
{'label':'degung','value':'degung'},
{'label':'delta blues','value':'delta blues'},
{'label':'dementia','value':'dementia'},
{'label':'desert rock','value':'desert rock'},
{'label':'desi','value':'desi'},
{'label':'detroit blues','value':'detroit blues'},
{'label':'detroit techno','value':'detroit techno'},
{'label':'dhamar','value':'dhamar'},
{'label':'dhimotiká','value':'dhimotiká'},
{'label':'dhrupad','value':'dhrupad'},
{'label':'dhun','value':'dhun'},
{'label':'digital hardcore','value':'digital hardcore'},
{'label':'dirge','value':'dirge'},
{'label':'dirty dutch','value':'dirty dutch'},
{'label':'dirty rap','value':'dirty rap'},
{'label':'dirty rap/pornocore','value':'dirty rap/pornocore'},
{'label':'dirty south','value':'dirty south'},
{'label':'disco','value':'disco'},
{'label':'disco house','value':'disco house'},
{'label':'disco polo','value':'disco polo'},
{'label':'disney','value':'disney'},
{'label':'disney hardcore','value':'disney hardcore'},
{'label':'disney pop','value':'disney pop'},
{'label':'diva house','value':'diva house'},
{'label':'divine rock','value':'divine rock'},
{'label':'dixieland','value':'dixieland'},
{'label':'dixieland jazz','value':'dixieland jazz'},
{'label':'djambadon','value':'djambadon'},
{'label':'djent','value':'djent'},
{'label':'dodompa','value':'dodompa'},
{'label':'doina','value':'doina'},
{'label':'dombola','value':'dombola'},
{'label':'dondang sayang','value':'dondang sayang'},
{'label':'donegal fiddle tradition','value':'donegal fiddle tradition'},
{'label':'dongjing','value':'dongjing'},
{'label':'doo wop','value':'doo wop'},
{'label':'doom metal','value':'doom metal'},
{'label':'doomcore','value':'doomcore'},
{'label':'downtempo','value':'downtempo'},
{'label':'drag','value':'drag'},
{'label':'dream pop','value':'dream pop'},
{'label':'drone doom','value':'drone doom'},
{'label':'drone metal','value':'drone metal'},
{'label':'drone music','value':'drone music'},
{'label':'dronology','value':'dronology'},
{'label':'drum and bass','value':'drum and bass'},
{'label':'dub','value':'dub'},
{'label':'dub house','value':'dub house'},
{'label':'dubanguthu','value':'dubanguthu'},
{'label':'dubstep','value':'dubstep'},
{'label':'dubtronica','value':'dubtronica'},
{'label':'dunedin sound','value':'dunedin sound'},
{'label':'dunun','value':'dunun'},
{'label':'dutch jazz','value':'dutch jazz'},
{'label':'décima','value':'décima'},
{'label':'early music','value':'early music'},
{'label':'east coast blues','value':'east coast blues'},
{'label':'east coast hip hop','value':'east coast hip hop'},
{'label':'easy listening','value':'easy listening'},
{'label':'electric blues','value':'electric blues'},
{'label':'electric folk','value':'electric folk'},
{'label':'electro','value':'electro'},
{'label':'electro backbeat','value':'electro backbeat'},
{'label':'electro hop','value':'electro hop'},
{'label':'electro house','value':'electro house'},
{'label':'electro punk','value':'electro punk'},
{'label':'electro-industrial','value':'electro-industrial'},
{'label':'electro-swing','value':'electro-swing'},
{'label':'electroclash','value':'electroclash'},
{'label':'electrofunk','value':'electrofunk'},
{'label':'electronic','value':'electronic'},
{'label':'electronic art music','value':'electronic art music'},
{'label':'electronic body music','value':'electronic body music'},
{'label':'electronic dance','value':'electronic dance'},
{'label':'electronic luk thung','value':'electronic luk thung'},
{'label':'electronic music','value':'electronic music'},
{'label':'electronic rock','value':'electronic rock'},
{'label':'electronica','value':'electronica'},
{'label':'electropop','value':'electropop'},
{'label':'elevator music','value':'elevator music'},
{'label':'emo','value':'emo'},
{'label':'emo pop','value':'emo pop'},
{'label':'emo rap','value':'emo rap'},
{'label':'emocore','value':'emocore'},
{'label':'emotronic','value':'emotronic'},
{'label':'enka','value':'enka'},
{'label':'eremwu eu','value':'eremwu eu'},
{'label':'essential rock','value':'essential rock'},
{'label':'ethereal pop','value':'ethereal pop'},
{'label':'ethereal wave','value':'ethereal wave'},
{'label':'euro','value':'euro'},
{'label':'euro disco','value':'euro disco'},
{'label':'eurobeat','value':'eurobeat'},
{'label':'eurodance','value':'eurodance'},
{'label':'europop','value':'europop'},
{'label':'eurotrance','value':'eurotrance'},
{'label':'eurourban','value':'eurourban'},
{'label':'exotica','value':'exotica'},
{'label':'experimental music','value':'experimental music'},
{'label':'experimental noise','value':'experimental noise'},
{'label':'experimental pop','value':'experimental pop'},
{'label':'experimental rock','value':'experimental rock'},
{'label':'extreme metal','value':'extreme metal'},
{'label':'ezengileer','value':'ezengileer'},
{'label':'fado','value':'fado'},
{'label':'falak','value':'falak'},
{'label':'fandango','value':'fandango'},
{'label':'farruca','value':'farruca'},
{'label':'fife and drum blues','value':'fife and drum blues'},
{'label':'filk','value':'filk'},
{'label':'film score','value':'film score'},
{'label':'filmi','value':'filmi'},
{'label':'filmi-ghazal','value':'filmi-ghazal'},
{'label':'finger-style','value':'finger-style'},
{'label':'fjatpangarri','value':'fjatpangarri'},
{'label':'flamenco','value':'flamenco'},
{'label':'flamenco rumba','value':'flamenco rumba'},
{'label':'flower power','value':'flower power'},
{'label':'foaie verde','value':'foaie verde'},
{'label':'fofa','value':'fofa'},
{'label':'folk hop','value':'folk hop'},
{'label':'folk metal','value':'folk metal'},
{'label':'folk music','value':'folk music'},
{'label':'folk pop','value':'folk pop'},
{'label':'folk punk','value':'folk punk'},
{'label':'folk rock','value':'folk rock'},
{'label':'folktronica','value':'folktronica'},
{'label':'forró','value':'forró'},
{'label':'franco-country','value':'franco-country'},
{'label':'freak-folk','value':'freak-folk'},
{'label':'freakbeat','value':'freakbeat'},
{'label':'free improvisation','value':'free improvisation'},
{'label':'free jazz','value':'free jazz'},
{'label':'free music','value':'free music'},
{'label':'freestyle','value':'freestyle'},
{'label':'freestyle house','value':'freestyle house'},
{'label':'freetekno','value':'freetekno'},
{'label':'french pop','value':'french pop'},
{'label':'frenchcore','value':'frenchcore'},
{'label':'frevo','value':'frevo'},
{'label':'fricote','value':'fricote'},
{'label':'fuji','value':'fuji'},
{'label':'fuji music','value':'fuji music'},
{'label':'fulia','value':'fulia'},
{'label':'full on','value':'full on'},
{'label':'funaná','value':'funaná'},
{'label':'funeral doom','value':'funeral doom'},
{'label':'funk','value':'funk'},
{'label':'funk metal','value':'funk metal'},
{'label':'funk rock','value':'funk rock'},
{'label':'funkcore','value':'funkcore'},
{'label':'funky house','value':'funky house'},
{'label':'furniture music','value':'furniture music'},
{'label':'fusion jazz','value':'fusion jazz'},
{'label':'g-funk','value':'g-funk'},
{'label':'gaana','value':'gaana'},
{'label':'gabba','value':'gabba'},
{'label':'gabber','value':'gabber'},
{'label':'gagaku','value':'gagaku'},
{'label':'gaikyoku','value':'gaikyoku'},
{'label':'gaita','value':'gaita'},
{'label':'galant','value':'galant'},
{'label':'gamad','value':'gamad'},
{'label':'gambang kromong','value':'gambang kromong'},
{'label':'gamelan','value':'gamelan'},
{'label':'gamelan angklung','value':'gamelan angklung'},
{'label':'gamelan bang','value':'gamelan bang'},
{'label':'gamelan bebonangan','value':'gamelan bebonangan'},
{'label':'gamelan buh','value':'gamelan buh'},
{'label':'gamelan degung','value':'gamelan degung'},
{'label':'gamelan gede','value':'gamelan gede'},
{'label':'gamelan kebyar','value':'gamelan kebyar'},
{'label':'gamelan salendro','value':'gamelan salendro'},
{'label':'gamelan selunding','value':'gamelan selunding'},
{'label':'gamelan semar pegulingan','value':'gamelan semar pegulingan'},
{'label':'gamewave','value':'gamewave'},
{'label':'gammeldans','value':'gammeldans'},
{'label':'gandrung','value':'gandrung'},
{'label':'gangsta rap','value':'gangsta rap'},
{'label':'gar','value':'gar'},
{'label':'garage rock','value':'garage rock'},
{'label':'garrotin','value':'garrotin'},
{'label':'gavotte','value':'gavotte'},
{'label':'gelugpa chanting','value':'gelugpa chanting'},
{'label':'gender wayang','value':'gender wayang'},
{'label':'gending','value':'gending'},
{'label':'german folk music','value':'german folk music'},
{'label':'gharbi','value':'gharbi'},
{'label':'gharnati','value':'gharnati'},
{'label':'ghazal','value':'ghazal'},
{'label':'ghazal-song','value':'ghazal-song'},
{'label':'ghetto house','value':'ghetto house'},
{'label':'ghettotech','value':'ghettotech'},
{'label':'girl group','value':'girl group'},
{'label':'glam metal','value':'glam metal'},
{'label':'glam punk','value':'glam punk'},
{'label':'glam rock','value':'glam rock'},
{'label':'glitch','value':'glitch'},
{'label':'gnawa','value':'gnawa'},
{'label':'go-go','value':'go-go'},
{'label':'goa','value':'goa'},
{'label':'goa trance','value':'goa trance'},
{'label':'gong-chime music','value':'gong-chime music'},
{'label':'goombay','value':'goombay'},
{'label':'goregrind','value':'goregrind'},
{'label':'goshu ondo','value':'goshu ondo'},
{'label':'gospel music','value':'gospel music'},
{'label':'gothic metal','value':'gothic metal'},
{'label':'gothic rock','value':'gothic rock'},
{'label':'granadinas','value':'granadinas'},
{'label':'grebo','value':'grebo'},
{'label':'gregorian chant','value':'gregorian chant'},
{'label':'grime','value':'grime'},
{'label':'grindcore','value':'grindcore'},
{'label':'groove metal','value':'groove metal'},
{'label':'group sounds','value':'group sounds'},
{'label':'grunge','value':'grunge'},
{'label':'grupera','value':'grupera'},
{'label':'guaguanbo','value':'guaguanbo'},
{'label':'guajira','value':'guajira'},
{'label':'guasca','value':'guasca'},
{'label':'guitarra baiana','value':'guitarra baiana'},
{'label':'guitarradas','value':'guitarradas'},
{'label':'gumbe','value':'gumbe'},
{'label':'gunchei','value':'gunchei'},
{'label':'gunka','value':'gunka'},
{'label':'guoyue','value':'guoyue'},
{'label':'gwo ka','value':'gwo ka'},
{'label':'gwo ka moderne','value':'gwo ka moderne'},
{'label':'gypsy jazz','value':'gypsy jazz'},
{'label':'gypsy punk','value':'gypsy punk'},
{'label':'gypsybilly','value':'gypsybilly'},
{'label':'gyu ke','value':'gyu ke'},
{'label':'habanera','value':'habanera'},
{'label':'hajnali','value':'hajnali'},
{'label':'hakka','value':'hakka'},
{'label':'halling','value':'halling'},
{'label':'hambo','value':'hambo'},
{'label':'hands up','value':'hands up'},
{'label':'hapa haole','value':'hapa haole'},
{'label':'happy hardcore','value':'happy hardcore'},
{'label':'haqibah','value':'haqibah'},
{'label':'hard','value':'hard'},
{'label':'hard bop','value':'hard bop'},
{'label':'hard house','value':'hard house'},
{'label':'hard rock','value':'hard rock'},
{'label':'hard trance','value':'hard trance'},
{'label':'hardcore hip hop','value':'hardcore hip hop'},
{'label':'hardcore metal','value':'hardcore metal'},
{'label':'hardcore punk','value':'hardcore punk'},
{'label':'hardcore techno','value':'hardcore techno'},
{'label':'hardstyle','value':'hardstyle'},
{'label':'harepa','value':'harepa'},
{'label':'harmonica blues','value':'harmonica blues'},
{'label':'hasaposérviko','value':'hasaposérviko'},
{'label':'heart attack','value':'heart attack'},
{'label':'heartland rock','value':'heartland rock'},
{'label':'heavy beat','value':'heavy beat'},
{'label':'heavy metal','value':'heavy metal'},
{'label':'hesher','value':'hesher'},
{'label':'hi-nrg','value':'hi-nrg'},
{'label':'highlands','value':'highlands'},
{'label':'highlife','value':'highlife'},
{'label':'highlife fusion','value':'highlife fusion'},
{'label':'hillybilly music','value':'hillybilly music'},
{'label':'hindustani classical music','value':'hindustani classical music'},
{'label':'hip hop','value':'hip hop'},
{'label':'hip hop & rap','value':'hip hop & rap'},
{'label':'hip hop soul','value':'hip hop soul'},
{'label':'hip house','value':'hip house'},
{'label':'hiplife','value':'hiplife'},
{'label':'hiragasy','value':'hiragasy'},
{'label':'hiva usu','value':'hiva usu'},
{'label':'hong kong and cantonese pop','value':'hong kong and cantonese pop'},
{'label':'hong kong english pop','value':'hong kong english pop'},
{'label':'honky tonk','value':'honky tonk'},
{'label':'honkyoku','value':'honkyoku'},
{'label':'hora lunga','value':'hora lunga'},
{'label':'hornpipe','value':'hornpipe'},
{'label':'horror punk','value':'horror punk'},
{'label':'horrorcore','value':'horrorcore'},
{'label':'horrorcore rap','value':'horrorcore rap'},
{'label':'house','value':'house'},
{'label':'house music','value':'house music'},
{'label':'hua\'er','value':'hua\'er'},
{'label':'huasteco','value':'huasteco'},
{'label':'huayno','value':'huayno'},
{'label':'hula','value':'hula'},
{'label':'humppa','value':'humppa'},
{'label':'hunguhungu','value':'hunguhungu'},
{'label':'hyangak','value':'hyangak'},
{'label':'hymn','value':'hymn'},
{'label':'hyphy','value':'hyphy'},
{'label':'hát chau van','value':'hát chau van'},
{'label':'hát chèo','value':'hát chèo'},
{'label':'hát cãi luong','value':'hát cãi luong'},
{'label':'hát tuồng','value':'hát tuồng'},
{'label':'ibiza music','value':'ibiza music'},
{'label':'icaro','value':'icaro'},
{'label':'idm','value':'idm'},
{'label':'igbo music','value':'igbo music'},
{'label':'ijexá','value':'ijexá'},
{'label':'ilahije','value':'ilahije'},
{'label':'illbient','value':'illbient'},
{'label':'impressionist music','value':'impressionist music'},
{'label':'improvisational','value':'improvisational'},
{'label':'incidental music','value':'incidental music'},
{'label':'indian pop','value':'indian pop'},
{'label':'indie folk','value':'indie folk'},
{'label':'indie music','value':'indie music'},
{'label':'indie pop','value':'indie pop'},
{'label':'indie rock','value':'indie rock'},
{'label':'indietronica','value':'indietronica'},
{'label':'indo jazz','value':'indo jazz'},
{'label':'indo rock','value':'indo rock'},
{'label':'indonesian pop','value':'indonesian pop'},
{'label':'indoyíftika','value':'indoyíftika'},
{'label':'industrial death metal','value':'industrial death metal'},
{'label':'industrial hip-hop','value':'industrial hip-hop'},
{'label':'industrial metal','value':'industrial metal'},
{'label':'industrial music','value':'industrial music'},
{'label':'industrial musical','value':'industrial musical'},
{'label':'industrial rock','value':'industrial rock'},
{'label':'instrumental rock','value':'instrumental rock'},
{'label':'intelligent dance music','value':'intelligent dance music'},
{'label':'international latin','value':'international latin'},
{'label':'inuit music','value':'inuit music'},
{'label':'iranian pop','value':'iranian pop'},
{'label':'irish folk','value':'irish folk'},
{'label':'irish rebel music','value':'irish rebel music'},
{'label':'iscathamiya','value':'iscathamiya'},
{'label':'isicathamiya','value':'isicathamiya'},
{'label':'isikhwela jo','value':'isikhwela jo'},
{'label':'island','value':'island'},
{'label':'isolationist','value':'isolationist'},
{'label':'italo dance','value':'italo dance'},
{'label':'italo disco','value':'italo disco'},
{'label':'italo house','value':'italo house'},
{'label':'itsmeños','value':'itsmeños'},
{'label':'izvorna bosanska muzika','value':'izvorna bosanska muzika'},
{'label':'j\'ouvert','value':'j\'ouvert'},
{'label':'j-fusion','value':'j-fusion'},
{'label':'j-pop','value':'j-pop'},
{'label':'j-rock','value':'j-rock'},
{'label':'jaipongan','value':'jaipongan'},
{'label':'jaliscienses','value':'jaliscienses'},
{'label':'jam band','value':'jam band'},
{'label':'jam rock','value':'jam rock'},
{'label':'jamana kura','value':'jamana kura'},
{'label':'jamrieng samai','value':'jamrieng samai'},
{'label':'jangle pop','value':'jangle pop'},
{'label':'japanese pop','value':'japanese pop'},
{'label':'jarana','value':'jarana'},
{'label':'jariang','value':'jariang'},
{'label':'jarochos','value':'jarochos'},
{'label':'jawaiian','value':'jawaiian'},
{'label':'jazz','value':'jazz'},
{'label':'jazz blues','value':'jazz blues'},
{'label':'jazz fusion','value':'jazz fusion'},
{'label':'jazz metal','value':'jazz metal'},
{'label':'jazz rap','value':'jazz rap'},
{'label':'jazz-funk','value':'jazz-funk'},
{'label':'jazz-rock','value':'jazz-rock'},
{'label':'jegog','value':'jegog'},
{'label':'jenkka','value':'jenkka'},
{'label':'jesus music','value':'jesus music'},
{'label':'jibaro','value':'jibaro'},
{'label':'jig','value':'jig'},
{'label':'jig punk','value':'jig punk'},
{'label':'jing ping','value':'jing ping'},
{'label':'jingle','value':'jingle'},
{'label':'jit','value':'jit'},
{'label':'jitterbug','value':'jitterbug'},
{'label':'jive','value':'jive'},
{'label':'joged','value':'joged'},
{'label':'joged bumbung','value':'joged bumbung'},
{'label':'joik','value':'joik'},
{'label':'jonnycore','value':'jonnycore'},
{'label':'joropo','value':'joropo'},
{'label':'jota','value':'jota'},
{'label':'jtek','value':'jtek'},
{'label':'jug band','value':'jug band'},
{'label':'jujitsu','value':'jujitsu'},
{'label':'juju','value':'juju'},
{'label':'juke joint blues','value':'juke joint blues'},
{'label':'jump blues','value':'jump blues'},
{'label':'jumpstyle','value':'jumpstyle'},
{'label':'jungle','value':'jungle'},
{'label':'junkanoo','value':'junkanoo'},
{'label':'juré','value':'juré'},
{'label':'jùjú','value':'jùjú'},
{'label':'k-pop','value':'k-pop'},
{'label':'kaba','value':'kaba'},
{'label':'kabuki','value':'kabuki'},
{'label':'kachāshī','value':'kachāshī'},
{'label':'kadans','value':'kadans'},
{'label':'kagok','value':'kagok'},
{'label':'kagyupa chanting','value':'kagyupa chanting'},
{'label':'kaiso','value':'kaiso'},
{'label':'kalamatianó','value':'kalamatianó'},
{'label':'kalattuut','value':'kalattuut'},
{'label':'kalinda','value':'kalinda'},
{'label':'kamba pop','value':'kamba pop'},
{'label':'kan ha diskan','value':'kan ha diskan'},
{'label':'kansas city blues','value':'kansas city blues'},
{'label':'kantrum','value':'kantrum'},
{'label':'kantádhes','value':'kantádhes'},
{'label':'kargyraa','value':'kargyraa'},
{'label':'karma','value':'karma'},
{'label':'kaseko','value':'kaseko'},
{'label':'katajjaq','value':'katajjaq'},
{'label':'kawachi ondo','value':'kawachi ondo'},
{'label':'kayōkyoku','value':'kayōkyoku'},
{'label':'ke-kwe','value':'ke-kwe'},
{'label':'kebyar','value':'kebyar'},
{'label':'kecak','value':'kecak'},
{'label':'kecapi suling','value':'kecapi suling'},
{'label':'kertok','value':'kertok'},
{'label':'khaleeji','value':'khaleeji'},
{'label':'khap','value':'khap'},
{'label':'khelimaski djili','value':'khelimaski djili'},
{'label':'khene','value':'khene'},
{'label':'khoomei','value':'khoomei'},
{'label':'khorovodi','value':'khorovodi'},
{'label':'khplam wai','value':'khplam wai'},
{'label':'khrung sai','value':'khrung sai'},
{'label':'khyal','value':'khyal'},
{'label':'kilapanda','value':'kilapanda'},
{'label':'kinko','value':'kinko'},
{'label':'kirtan','value':'kirtan'},
{'label':'kiwi rock','value':'kiwi rock'},
{'label':'kizomba','value':'kizomba'},
{'label':'klape','value':'klape'},
{'label':'klasik','value':'klasik'},
{'label':'klezmer','value':'klezmer'},
{'label':'kliningan','value':'kliningan'},
{'label':'kléftiko','value':'kléftiko'},
{'label':'kochare','value':'kochare'},
{'label':'kolomyjka','value':'kolomyjka'},
{'label':'komagaku','value':'komagaku'},
{'label':'kompa','value':'kompa'},
{'label':'konpa','value':'konpa'},
{'label':'korean pop','value':'korean pop'},
{'label':'koumpaneia','value':'koumpaneia'},
{'label':'kpanlogo','value':'kpanlogo'},
{'label':'krakowiak','value':'krakowiak'},
{'label':'krautrock','value':'krautrock'},
{'label':'kriti','value':'kriti'},
{'label':'kroncong','value':'kroncong'},
{'label':'krump','value':'krump'},
{'label':'krzesany','value':'krzesany'},
{'label':'kuduro','value':'kuduro'},
{'label':'kulintang','value':'kulintang'},
{'label':'kulning','value':'kulning'},
{'label':'kumina','value':'kumina'},
{'label':'kun-borrk','value':'kun-borrk'},
{'label':'kundere','value':'kundere'},
{'label':'kundiman','value':'kundiman'},
{'label':'kussundé','value':'kussundé'},
{'label':'kutumba wake','value':'kutumba wake'},
{'label':'kveding','value':'kveding'},
{'label':'kvæði','value':'kvæði'},
{'label':'kwaito','value':'kwaito'},
{'label':'kwassa kwassa','value':'kwassa kwassa'},
{'label':'kwela','value':'kwela'},
{'label':'käng','value':'käng'},
{'label':'kélé','value':'kélé'},
{'label':'kĩkũyũ pop','value':'kĩkũyũ pop'},
{'label':'la la','value':'la la'},
{'label':'latin american','value':'latin american'},
{'label':'latin jazz','value':'latin jazz'},
{'label':'latin pop','value':'latin pop'},
{'label':'latin rap','value':'latin rap'},
{'label':'lavway','value':'lavway'},
{'label':'laïko','value':'laïko'},
{'label':'laïkó','value':'laïkó'},
{'label':'le leagan','value':'le leagan'},
{'label':'legényes','value':'legényes'},
{'label':'lelio','value':'lelio'},
{'label':'letkajenkka','value':'letkajenkka'},
{'label':'levenslied','value':'levenslied'},
{'label':'lhamo','value':'lhamo'},
{'label':'lieder','value':'lieder'},
{'label':'light music','value':'light music'},
{'label':'light rock','value':'light rock'},
{'label':'likanos','value':'likanos'},
{'label':'liquid drum&bass','value':'liquid drum&bass'},
{'label':'liquid funk','value':'liquid funk'},
{'label':'liquindi','value':'liquindi'},
{'label':'llanera','value':'llanera'},
{'label':'llanto','value':'llanto'},
{'label':'lo-fi','value':'lo-fi'},
{'label':'lo-fi music','value':'lo-fi music'},
{'label':'loki djili','value':'loki djili'},
{'label':'long-song','value':'long-song'},
{'label':'louisiana blues','value':'louisiana blues'},
{'label':'louisiana swamp pop','value':'louisiana swamp pop'},
{'label':'lounge music','value':'lounge music'},
{'label':'lovers rock','value':'lovers rock'},
{'label':'lowercase','value':'lowercase'},
{'label':'lubbock sound','value':'lubbock sound'},
{'label':'lucknavi thumri','value':'lucknavi thumri'},
{'label':'luhya omutibo','value':'luhya omutibo'},
{'label':'luk grung','value':'luk grung'},
{'label':'lullaby','value':'lullaby'},
{'label':'lundu','value':'lundu'},
{'label':'lundum','value':'lundum'},
{'label':'m-base','value':'m-base'},
{'label':'madchester','value':'madchester'},
{'label':'madrigal','value':'madrigal'},
{'label':'mafioso rap','value':'mafioso rap'},
{'label':'maglaal','value':'maglaal'},
{'label':'magnificat','value':'magnificat'},
{'label':'mahori','value':'mahori'},
{'label':'mainstream jazz','value':'mainstream jazz'},
{'label':'makossa','value':'makossa'},
{'label':'makossa-soukous','value':'makossa-soukous'},
{'label':'malagueñas','value':'malagueñas'},
{'label':'malawian jazz','value':'malawian jazz'},
{'label':'malhun','value':'malhun'},
{'label':'maloya','value':'maloya'},
{'label':'maluf','value':'maluf'},
{'label':'maluka','value':'maluka'},
{'label':'mambo','value':'mambo'},
{'label':'manaschi','value':'manaschi'},
{'label':'mandarin pop','value':'mandarin pop'},
{'label':'manding swing','value':'manding swing'},
{'label':'mango','value':'mango'},
{'label':'mangue bit','value':'mangue bit'},
{'label':'mangulina','value':'mangulina'},
{'label':'manikay','value':'manikay'},
{'label':'manila sound','value':'manila sound'},
{'label':'manouche','value':'manouche'},
{'label':'manzuma','value':'manzuma'},
{'label':'mapouka','value':'mapouka'},
{'label':'mapouka-serré','value':'mapouka-serré'},
{'label':'marabi','value':'marabi'},
{'label':'maracatu','value':'maracatu'},
{'label':'marga','value':'marga'},
{'label':'mariachi','value':'mariachi'},
{'label':'marimba','value':'marimba'},
{'label':'marinera','value':'marinera'},
{'label':'marrabenta','value':'marrabenta'},
{'label':'martial industrial','value':'martial industrial'},
{'label':'martinetes','value':'martinetes'},
{'label':'maskanda','value':'maskanda'},
{'label':'mass','value':'mass'},
{'label':'matamuerte','value':'matamuerte'},
{'label':'math rock','value':'math rock'},
{'label':'mathcore','value':'mathcore'},
{'label':'matt bello','value':'matt bello'},
{'label':'maxixe','value':'maxixe'},
{'label':'mazurka','value':'mazurka'},
{'label':'mbalax','value':'mbalax'},
{'label':'mbaqanga','value':'mbaqanga'},
{'label':'mbube','value':'mbube'},
{'label':'mbumba','value':'mbumba'},
{'label':'medh','value':'medh'},
{'label':'medieval folk rock','value':'medieval folk rock'},
{'label':'medieval metal','value':'medieval metal'},
{'label':'medieval music','value':'medieval music'},
{'label':'meditation','value':'meditation'},
{'label':'mejorana','value':'mejorana'},
{'label':'melhoun','value':'melhoun'},
{'label':'melhûn','value':'melhûn'},
{'label':'melodic black metal','value':'melodic black metal'},
{'label':'melodic death metal','value':'melodic death metal'},
{'label':'melodic hardcore','value':'melodic hardcore'},
{'label':'melodic metalcore','value':'melodic metalcore'},
{'label':'melodic music','value':'melodic music'},
{'label':'melodic trance','value':'melodic trance'},
{'label':'memphis blues','value':'memphis blues'},
{'label':'memphis rap','value':'memphis rap'},
{'label':'memphis soul','value':'memphis soul'},
{'label':'mento','value':'mento'},
{'label':'merengue','value':'merengue'},
{'label':'merengue típico moderno','value':'merengue típico moderno'},
{'label':'merengue-bomba','value':'merengue-bomba'},
{'label':'meringue','value':'meringue'},
{'label':'merseybeat','value':'merseybeat'},
{'label':'metal','value':'metal'},
{'label':'metalcore','value':'metalcore'},
{'label':'metallic hardcore','value':'metallic hardcore'},
{'label':'mexican pop','value':'mexican pop'},
{'label':'mexican rock','value':'mexican rock'},
{'label':'mexican son','value':'mexican son'},
{'label':'meykhana','value':'meykhana'},
{'label':'mezwed','value':'mezwed'},
{'label':'miami bass','value':'miami bass'},
{'label':'microhouse','value':'microhouse'},
{'label':'middle of the road','value':'middle of the road'},
{'label':'midwest hip hop','value':'midwest hip hop'},
{'label':'milonga','value':'milonga'},
{'label':'min\'yo','value':'min\'yo'},
{'label':'mineras','value':'mineras'},
{'label':'mini compas','value':'mini compas'},
{'label':'mini-jazz','value':'mini-jazz'},
{'label':'minimal techno','value':'minimal techno'},
{'label':'minimalist music','value':'minimalist music'},
{'label':'minimalist trance','value':'minimalist trance'},
{'label':'minneapolis sound','value':'minneapolis sound'},
{'label':'minstrel show','value':'minstrel show'},
{'label':'minuet','value':'minuet'},
{'label':'mirolóyia','value':'mirolóyia'},
{'label':'modal jazz','value':'modal jazz'},
{'label':'modern classical music','value':'modern classical music'},
{'label':'modern laika','value':'modern laika'},
{'label':'modern rock','value':'modern rock'},
{'label':'modinha','value':'modinha'},
{'label':'mohabelo','value':'mohabelo'},
{'label':'montuno','value':'montuno'},
{'label':'monumental dance','value':'monumental dance'},
{'label':'mor lam','value':'mor lam'},
{'label':'mor lam sing','value':'mor lam sing'},
{'label':'morna','value':'morna'},
{'label':'motorpop','value':'motorpop'},
{'label':'motown','value':'motown'},
{'label':'mozambique','value':'mozambique'},
{'label':'mpb','value':'mpb'},
{'label':'mugam','value':'mugam'},
{'label':'multicultural','value':'multicultural'},
{'label':'murga','value':'murga'},
{'label':'musette','value':'musette'},
{'label':'museve','value':'museve'},
{'label':'mushroom jazz','value':'mushroom jazz'},
{'label':'music drama','value':'music drama'},
{'label':'music hall','value':'music hall'},
{'label':'musiqi-e assil','value':'musiqi-e assil'},
{'label':'musique concrète','value':'musique concrète'},
{'label':'mutuashi','value':'mutuashi'},
{'label':'muwashshah','value':'muwashshah'},
{'label':'muzak','value':'muzak'},
{'label':'méringue','value':'méringue'},
{'label':'música campesina','value':'música campesina'},
{'label':'música criolla','value':'música criolla'},
{'label':'música de la interior','value':'música de la interior'},
{'label':'música llanera','value':'música llanera'},
{'label':'música nordestina','value':'música nordestina'},
{'label':'música popular brasileira','value':'música popular brasileira'},
{'label':'música tropical','value':'música tropical'},
{'label':'nagauta','value':'nagauta'},
{'label':'nakasi','value':'nakasi'},
{'label':'nangma','value':'nangma'},
{'label':'nanguan','value':'nanguan'},
{'label':'narcocorrido','value':'narcocorrido'},
{'label':'nardcore','value':'nardcore'},
{'label':'narodna muzika','value':'narodna muzika'},
{'label':'nasheed','value':'nasheed'},
{'label':'nashville sound','value':'nashville sound'},
{'label':'nashville sound/countrypolitan','value':'nashville sound/countrypolitan'},
{'label':'national socialist black metal','value':'national socialist black metal'},
{'label':'naturalismo','value':'naturalismo'},
{'label':'nederpop','value':'nederpop'},
{'label':'neo soul','value':'neo soul'},
{'label':'neo-classical metal','value':'neo-classical metal'},
{'label':'neo-medieval','value':'neo-medieval'},
{'label':'neo-prog','value':'neo-prog'},
{'label':'neo-psychedelia','value':'neo-psychedelia'},
{'label':'neoclassical','value':'neoclassical'},
{'label':'neoclassical music','value':'neoclassical music'},
{'label':'neofolk','value':'neofolk'},
{'label':'neotraditional country','value':'neotraditional country'},
{'label':'nerdcore','value':'nerdcore'},
{'label':'neue deutsche härte','value':'neue deutsche härte'},
{'label':'neue deutsche welle','value':'neue deutsche welle'},
{'label':'new age music','value':'new age music'},
{'label':'new beat','value':'new beat'},
{'label':'new instrumental','value':'new instrumental'},
{'label':'new jack swing','value':'new jack swing'},
{'label':'new orleans blues','value':'new orleans blues'},
{'label':'new orleans jazz','value':'new orleans jazz'},
{'label':'new pop','value':'new pop'},
{'label':'new prog','value':'new prog'},
{'label':'new rave','value':'new rave'},
{'label':'new romantic','value':'new romantic'},
{'label':'new school hip hop','value':'new school hip hop'},
{'label':'new taiwanese song','value':'new taiwanese song'},
{'label':'new wave','value':'new wave'},
{'label':'new wave of british heavy metal','value':'new wave of british heavy metal'},
{'label':'new wave of new wave','value':'new wave of new wave'},
{'label':'new weird america','value':'new weird america'},
{'label':'new york blues','value':'new york blues'},
{'label':'new york house','value':'new york house'},
{'label':'newgrass','value':'newgrass'},
{'label':'nganja','value':'nganja'},
{'label':'niche','value':'niche'},
{'label':'nightcore','value':'nightcore'},
{'label':'nintendocore','value':'nintendocore'},
{'label':'nisiótika','value':'nisiótika'},
{'label':'no wave','value':'no wave'},
{'label':'noh','value':'noh'},
{'label':'noise music','value':'noise music'},
{'label':'noise pop','value':'noise pop'},
{'label':'noise rock','value':'noise rock'},
{'label':'nongak','value':'nongak'},
{'label':'norae undong','value':'norae undong'},
{'label':'nordic folk dance music','value':'nordic folk dance music'},
{'label':'nordic folk music','value':'nordic folk music'},
{'label':'nortec','value':'nortec'},
{'label':'norteño','value':'norteño'},
{'label':'northern soul','value':'northern soul'},
{'label':'nota','value':'nota'},
{'label':'nu breaks','value':'nu breaks'},
{'label':'nu jazz','value':'nu jazz'},
{'label':'nu metal','value':'nu metal'},
{'label':'nu soul','value':'nu soul'},
{'label':'nueva canción','value':'nueva canción'},
{'label':'nyatiti','value':'nyatiti'},
{'label':'néo kýma','value':'néo kýma'},
{'label':'obscuro','value':'obscuro'},
{'label':'oi!','value':'oi!'},
{'label':'old school hip hop','value':'old school hip hop'},
{'label':'old-time','value':'old-time'},
{'label':'oldies','value':'oldies'},
{'label':'olonkho','value':'olonkho'},
{'label':'oltului','value':'oltului'},
{'label':'ondo','value':'ondo'},
{'label':'opera','value':'opera'},
{'label':'operatic pop','value':'operatic pop'},
{'label':'oratorio','value':'oratorio'},
{'label':'orchestra','value':'orchestra'},
{'label':'organ trio','value':'organ trio'},
{'label':'organic ambient','value':'organic ambient'},
{'label':'organum','value':'organum'},
{'label':'orgel','value':'orgel'},
{'label':'oriental metal','value':'oriental metal'},
{'label':'ottava rima','value':'ottava rima'},
{'label':'outlaw country','value':'outlaw country'},
{'label':'outsider music','value':'outsider music'},
{'label':'p-funk','value':'p-funk'},
{'label':'pagan metal','value':'pagan metal'},
{'label':'pagan rock','value':'pagan rock'},
{'label':'pagode','value':'pagode'},
{'label':'paisley underground','value':'paisley underground'},
{'label':'palm wine','value':'palm wine'},
{'label':'palm-wine','value':'palm-wine'},
{'label':'pambiche','value':'pambiche'},
{'label':'panambih','value':'panambih'},
{'label':'panchai baja','value':'panchai baja'},
{'label':'panchavadyam','value':'panchavadyam'},
{'label':'pansori','value':'pansori'},
{'label':'paranda','value':'paranda'},
{'label':'parang','value':'parang'},
{'label':'parody','value':'parody'},
{'label':'parranda','value':'parranda'},
{'label':'partido alto','value':'partido alto'},
{'label':'pasillo','value':'pasillo'},
{'label':'patriotic','value':'patriotic'},
{'label':'peace punk','value':'peace punk'},
{'label':'pelimanni music','value':'pelimanni music'},
{'label':'petenera','value':'petenera'},
{'label':'peyote song','value':'peyote song'},
{'label':'philadelphia soul','value':'philadelphia soul'},
{'label':'piano blues','value':'piano blues'},
{'label':'piano rock','value':'piano rock'},
{'label':'piedmont blues','value':'piedmont blues'},
{'label':'pimba','value':'pimba'},
{'label':'pinoy pop','value':'pinoy pop'},
{'label':'pinoy rock','value':'pinoy rock'},
{'label':'pinpeat orchestra','value':'pinpeat orchestra'},
{'label':'piphat','value':'piphat'},
{'label':'piyyutim','value':'piyyutim'},
{'label':'plainchant','value':'plainchant'},
{'label':'plena','value':'plena'},
{'label':'pleng phua cheewit','value':'pleng phua cheewit'},
{'label':'pleng thai sakorn','value':'pleng thai sakorn'},
{'label':'political hip hop','value':'political hip hop'},
{'label':'polka','value':'polka'},
{'label':'polo','value':'polo'},
{'label':'polonaise','value':'polonaise'},
{'label':'pols','value':'pols'},
{'label':'polska','value':'polska'},
{'label':'pong lang','value':'pong lang'},
{'label':'pop','value':'pop'},
{'label':'pop folk','value':'pop folk'},
{'label':'pop music','value':'pop music'},
{'label':'pop punk','value':'pop punk'},
{'label':'pop rap','value':'pop rap'},
{'label':'pop rock','value':'pop rock'},
{'label':'pop sunda','value':'pop sunda'},
{'label':'pornocore','value':'pornocore'},
{'label':'porro','value':'porro'},
{'label':'post disco','value':'post disco'},
{'label':'post-britpop','value':'post-britpop'},
{'label':'post-disco','value':'post-disco'},
{'label':'post-grunge','value':'post-grunge'},
{'label':'post-hardcore','value':'post-hardcore'},
{'label':'post-industrial','value':'post-industrial'},
{'label':'post-metal','value':'post-metal'},
{'label':'post-minimalism','value':'post-minimalism'},
{'label':'post-punk','value':'post-punk'},
{'label':'post-rock','value':'post-rock'},
{'label':'post-romanticism','value':'post-romanticism'},
{'label':'pow-wow','value':'pow-wow'},
{'label':'power electronics','value':'power electronics'},
{'label':'power metal','value':'power metal'},
{'label':'power noise','value':'power noise'},
{'label':'power pop','value':'power pop'},
{'label':'powerviolence','value':'powerviolence'},
{'label':'ppongtchak','value':'ppongtchak'},
{'label':'praise song','value':'praise song'},
{'label':'program symphony','value':'program symphony'},
{'label':'progressive bluegrass','value':'progressive bluegrass'},
{'label':'progressive country','value':'progressive country'},
{'label':'progressive death metal','value':'progressive death metal'},
{'label':'progressive electronic','value':'progressive electronic'},
{'label':'progressive electronic music','value':'progressive electronic music'},
{'label':'progressive folk','value':'progressive folk'},
{'label':'progressive folk music','value':'progressive folk music'},
{'label':'progressive house','value':'progressive house'},
{'label':'progressive metal','value':'progressive metal'},
{'label':'progressive rock','value':'progressive rock'},
{'label':'progressive trance','value':'progressive trance'},
{'label':'protopunk','value':'protopunk'},
{'label':'psych folk','value':'psych folk'},
{'label':'psychedelic music','value':'psychedelic music'},
{'label':'psychedelic pop','value':'psychedelic pop'},
{'label':'psychedelic rock','value':'psychedelic rock'},
{'label':'psychedelic trance','value':'psychedelic trance'},
{'label':'psychobilly','value':'psychobilly'},
{'label':'punk blues','value':'punk blues'},
{'label':'punk cabaret','value':'punk cabaret'},
{'label':'punk jazz','value':'punk jazz'},
{'label':'punk rock','value':'punk rock'},
{'label':'punta','value':'punta'},
{'label':'punta rock','value':'punta rock'},
{'label':'qasidah','value':'qasidah'},
{'label':'qasidah modern','value':'qasidah modern'},
{'label':'qawwali','value':'qawwali'},
{'label':'quadrille','value':'quadrille'},
{'label':'quan ho','value':'quan ho'},
{'label':'queercore','value':'queercore'},
{'label':'quiet storm','value':'quiet storm'},
{'label':'rada','value':'rada'},
{'label':'raga','value':'raga'},
{'label':'raga rock','value':'raga rock'},
{'label':'ragga','value':'ragga'},
{'label':'ragga jungle','value':'ragga jungle'},
{'label':'raggamuffin','value':'raggamuffin'},
{'label':'ragtime','value':'ragtime'},
{'label':'rai','value':'rai'},
{'label':'rake-and-scrape','value':'rake-and-scrape'},
{'label':'ramkbach','value':'ramkbach'},
{'label':'ramvong','value':'ramvong'},
{'label':'ranchera','value':'ranchera'},
{'label':'rap','value':'rap'},
{'label':'rap metal','value':'rap metal'},
{'label':'rap rock','value':'rap rock'},
{'label':'rapcore','value':'rapcore'},
{'label':'rara','value':'rara'},
{'label':'rare groove','value':'rare groove'},
{'label':'rasiya','value':'rasiya'},
{'label':'rave','value':'rave'},
{'label':'raw rock','value':'raw rock'},
{'label':'raï','value':'raï'},
{'label':'rebetiko','value':'rebetiko'},
{'label':'red dirt','value':'red dirt'},
{'label':'reel','value':'reel'},
{'label':'reggae','value':'reggae'},
{'label':'reggae fusion','value':'reggae fusion'},
{'label':'reggae highlife','value':'reggae highlife'},
{'label':'reggaefusion','value':'reggaefusion'},
{'label':'reggaeton','value':'reggaeton'},
{'label':'rekilaulu','value':'rekilaulu'},
{'label':'relax music','value':'relax music'},
{'label':'religious','value':'religious'},
{'label':'rembetiko','value':'rembetiko'},
{'label':'renaissance music','value':'renaissance music'},
{'label':'requiem','value':'requiem'},
{'label':'rhapsody','value':'rhapsody'},
{'label':'rhyming spiritual','value':'rhyming spiritual'},
{'label':'rhythm & blues','value':'rhythm & blues'},
{'label':'rhythm and blues','value':'rhythm and blues'},
{'label':'ricercar','value':'ricercar'},
{'label':'riot grrrl','value':'riot grrrl'},
{'label':'rock','value':'rock'},
{'label':'rock and roll','value':'rock and roll'},
{'label':'rock en español','value':'rock en español'},
{'label':'rock opera','value':'rock opera'},
{'label':'rockabilly','value':'rockabilly'},
{'label':'rocksteady','value':'rocksteady'},
{'label':'rococo','value':'rococo'},
{'label':'romantic period in music','value':'romantic period in music'},
{'label':'rondeaux','value':'rondeaux'},
{'label':'ronggeng','value':'ronggeng'},
{'label':'roots reggae','value':'roots reggae'},
{'label':'roots rock','value':'roots rock'},
{'label':'roots rock reggae','value':'roots rock reggae'},
{'label':'rumba','value':'rumba'},
{'label':'russian pop','value':'russian pop'},
{'label':'rímur','value':'rímur'},
{'label':'sabar','value':'sabar'},
{'label':'sacred harp','value':'sacred harp'},
{'label':'sadcore','value':'sadcore'},
{'label':'saibara','value':'saibara'},
{'label':'sakara','value':'sakara'},
{'label':'salegy','value':'salegy'},
{'label':'salsa','value':'salsa'},
{'label':'salsa erotica','value':'salsa erotica'},
{'label':'salsa romantica','value':'salsa romantica'},
{'label':'saltarello','value':'saltarello'},
{'label':'samba','value':'samba'},
{'label':'samba-canção','value':'samba-canção'},
{'label':'samba-reggae','value':'samba-reggae'},
{'label':'samba-rock','value':'samba-rock'},
{'label':'sambai','value':'sambai'},
{'label':'sanjo','value':'sanjo'},
{'label':'sato kagura','value':'sato kagura'},
{'label':'sawt','value':'sawt'},
{'label':'saya','value':'saya'},
{'label':'scat','value':'scat'},
{'label':'schlager','value':'schlager'},
{'label':'schottisch','value':'schottisch'},
{'label':'schranz','value':'schranz'},
{'label':'scottish baroque music','value':'scottish baroque music'},
{'label':'screamo','value':'screamo'},
{'label':'scrumpy and western','value':'scrumpy and western'},
{'label':'sea shanty','value':'sea shanty'},
{'label':'sean nós','value':'sean nós'},
{'label':'second viennese school','value':'second viennese school'},
{'label':'sega music','value':'sega music'},
{'label':'seggae','value':'seggae'},
{'label':'seis','value':'seis'},
{'label':'semba','value':'semba'},
{'label':'sephardic music','value':'sephardic music'},
{'label':'serialism','value':'serialism'},
{'label':'set dance','value':'set dance'},
{'label':'sevdalinka','value':'sevdalinka'},
{'label':'sevillana','value':'sevillana'},
{'label':'shabab','value':'shabab'},
{'label':'shabad','value':'shabad'},
{'label':'shalako','value':'shalako'},
{'label':'shan\'ge','value':'shan\'ge'},
{'label':'shango','value':'shango'},
{'label':'shape note','value':'shape note'},
{'label':'shibuya-kei','value':'shibuya-kei'},
{'label':'shidaiqu','value':'shidaiqu'},
{'label':'shima uta','value':'shima uta'},
{'label':'shock rock','value':'shock rock'},
{'label':'shoegaze','value':'shoegaze'},
{'label':'shoegazer','value':'shoegazer'},
{'label':'shoka','value':'shoka'},
{'label':'shomyo','value':'shomyo'},
{'label':'show tune','value':'show tune'},
{'label':'sica','value':'sica'},
{'label':'siguiriyas','value':'siguiriyas'},
{'label':'silat','value':'silat'},
{'label':'sinawi','value':'sinawi'},
{'label':'singer-songwriter','value':'singer-songwriter'},
{'label':'situational','value':'situational'},
{'label':'ska','value':'ska'},
{'label':'ska punk','value':'ska punk'},
{'label':'skacore','value':'skacore'},
{'label':'skald','value':'skald'},
{'label':'skate punk','value':'skate punk'},
{'label':'skiffle','value':'skiffle'},
{'label':'slack-key guitar','value':'slack-key guitar'},
{'label':'slide','value':'slide'},
{'label':'slowcore','value':'slowcore'},
{'label':'sludge metal','value':'sludge metal'},
{'label':'slängpolska','value':'slängpolska'},
{'label':'smooth jazz','value':'smooth jazz'},
{'label':'soca','value':'soca'},
{'label':'soft rock','value':'soft rock'},
{'label':'son','value':'son'},
{'label':'son montuno','value':'son montuno'},
{'label':'son-batá','value':'son-batá'},
{'label':'sonata','value':'sonata'},
{'label':'songo','value':'songo'},
{'label':'songo-salsa','value':'songo-salsa'},
{'label':'sophisti-pop','value':'sophisti-pop'},
{'label':'soukous','value':'soukous'},
{'label':'soul','value':'soul'},
{'label':'soul blues','value':'soul blues'},
{'label':'soul jazz','value':'soul jazz'},
{'label':'soul music','value':'soul music'},
{'label':'soundtrack','value':'soundtrack'},
{'label':'southern gospel','value':'southern gospel'},
{'label':'southern harmony','value':'southern harmony'},
{'label':'southern hip hop','value':'southern hip hop'},
{'label':'southern metal','value':'southern metal'},
{'label':'southern rock','value':'southern rock'},
{'label':'southern soul','value':'southern soul'},
{'label':'space age pop','value':'space age pop'},
{'label':'space music','value':'space music'},
{'label':'space rock','value':'space rock'},
{'label':'spectralism','value':'spectralism'},
{'label':'speed garage','value':'speed garage'},
{'label':'speed metal','value':'speed metal'},
{'label':'speedcore','value':'speedcore'},
{'label':'spirituals','value':'spirituals'},
{'label':'spouge','value':'spouge'},
{'label':'sprechgesang','value':'sprechgesang'},
{'label':'square dance','value':'square dance'},
{'label':'squee','value':'squee'},
{'label':'st. louis blues','value':'st. louis blues'},
{'label':'steelband','value':'steelband'},
{'label':'stoner metal','value':'stoner metal'},
{'label':'stoner rock','value':'stoner rock'},
{'label':'straight edge','value':'straight edge'},
{'label':'strathspeys','value':'strathspeys'},
{'label':'stride','value':'stride'},
{'label':'string','value':'string'},
{'label':'string quartet','value':'string quartet'},
{'label':'sufi music','value':'sufi music'},
{'label':'suite','value':'suite'},
{'label':'sunshine pop','value':'sunshine pop'},
{'label':'suomirock','value':'suomirock'},
{'label':'super eurobeat','value':'super eurobeat'},
{'label':'surf ballad','value':'surf ballad'},
{'label':'surf instrumental','value':'surf instrumental'},
{'label':'surf music','value':'surf music'},
{'label':'surf pop','value':'surf pop'},
{'label':'surf rock','value':'surf rock'},
{'label':'swamp blues','value':'swamp blues'},
{'label':'swamp pop','value':'swamp pop'},
{'label':'swamp rock','value':'swamp rock'},
{'label':'swing','value':'swing'},
{'label':'swing music','value':'swing music'},
{'label':'swingbeat','value':'swingbeat'},
{'label':'sygyt','value':'sygyt'},
{'label':'symphonic black metal','value':'symphonic black metal'},
{'label':'symphonic metal','value':'symphonic metal'},
{'label':'symphonic poem','value':'symphonic poem'},
{'label':'symphonic rock','value':'symphonic rock'},
{'label':'symphony','value':'symphony'},
{'label':'synthpop','value':'synthpop'},
{'label':'synthpunk','value':'synthpunk'},
{'label':'t\'ong guitar','value':'t\'ong guitar'},
{'label':'taarab','value':'taarab'},
{'label':'tai tu','value':'tai tu'},
{'label':'taiwanese pop','value':'taiwanese pop'},
{'label':'tala','value':'tala'},
{'label':'talempong','value':'talempong'},
{'label':'tambu','value':'tambu'},
{'label':'tamburitza','value':'tamburitza'},
{'label':'tamil christian keerthanai','value':'tamil christian keerthanai'},
{'label':'tango','value':'tango'},
{'label':'tanguk','value':'tanguk'},
{'label':'tappa','value':'tappa'},
{'label':'tarana','value':'tarana'},
{'label':'tarantella','value':'tarantella'},
{'label':'taranto','value':'taranto'},
{'label':'tech','value':'tech'},
{'label':'tech house','value':'tech house'},
{'label':'tech trance','value':'tech trance'},
{'label':'technical death metal','value':'technical death metal'},
{'label':'technical metal','value':'technical metal'},
{'label':'techno','value':'techno'},
{'label':'technoid','value':'technoid'},
{'label':'technopop','value':'technopop'},
{'label':'techstep','value':'techstep'},
{'label':'techtonik','value':'techtonik'},
{'label':'teen pop','value':'teen pop'},
{'label':'tejano','value':'tejano'},
{'label':'tejano music','value':'tejano music'},
{'label':'tekno','value':'tekno'},
{'label':'tembang sunda','value':'tembang sunda'},
{'label':'texas blues','value':'texas blues'},
{'label':'thai pop','value':'thai pop'},
{'label':'thillana','value':'thillana'},
{'label':'thrash metal','value':'thrash metal'},
{'label':'thrashcore','value':'thrashcore'},
{'label':'thumri','value':'thumri'},
{'label':'tibetan pop','value':'tibetan pop'},
{'label':'tiento','value':'tiento'},
{'label':'timbila','value':'timbila'},
{'label':'tin pan alley','value':'tin pan alley'},
{'label':'tinga','value':'tinga'},
{'label':'tinku','value':'tinku'},
{'label':'toeshey','value':'toeshey'},
{'label':'togaku','value':'togaku'},
{'label':'trad jazz','value':'trad jazz'},
{'label':'traditional bluegrass','value':'traditional bluegrass'},
{'label':'traditional pop music','value':'traditional pop music'},
{'label':'trallalero','value':'trallalero'},
{'label':'trance','value':'trance'},
{'label':'tribal house','value':'tribal house'},
{'label':'trikitixa','value':'trikitixa'},
{'label':'trip hop','value':'trip hop'},
{'label':'trip rock','value':'trip rock'},
{'label':'trip-hop','value':'trip-hop'},
{'label':'tropicalia','value':'tropicalia'},
{'label':'tropicalismo','value':'tropicalismo'},
{'label':'tropipop','value':'tropipop'},
{'label':'truck-driving country','value':'truck-driving country'},
{'label':'tumba','value':'tumba'},
{'label':'turbo-folk','value':'turbo-folk'},
{'label':'turkish music','value':'turkish music'},
{'label':'turkish pop','value':'turkish pop'},
{'label':'turntablism','value':'turntablism'},
{'label':'tuvan throat-singing','value':'tuvan throat-singing'},
{'label':'twee pop','value':'twee pop'},
{'label':'twist','value':'twist'},
{'label':'two tone','value':'two tone'},
{'label':'táncház','value':'táncház'},
{'label':'uk garage','value':'uk garage'},
{'label':'uk pub rock','value':'uk pub rock'},
{'label':'unblack metal','value':'unblack metal'},
{'label':'underground music','value':'underground music'},
{'label':'uplifting','value':'uplifting'},
{'label':'uplifting trance','value':'uplifting trance'},
{'label':'urban cowboy','value':'urban cowboy'},
{'label':'urban folk','value':'urban folk'},
{'label':'urban jazz','value':'urban jazz'},
{'label':'vallenato','value':'vallenato'},
{'label':'vaudeville','value':'vaudeville'},
{'label':'venezuela','value':'venezuela'},
{'label':'verbunkos','value':'verbunkos'},
{'label':'verismo','value':'verismo'},
{'label':'video game music','value':'video game music'},
{'label':'viking metal','value':'viking metal'},
{'label':'villanella','value':'villanella'},
{'label':'virelai','value':'virelai'},
{'label':'vispop','value':'vispop'},
{'label':'visual kei','value':'visual kei'},
{'label':'visual music','value':'visual music'},
{'label':'vocal','value':'vocal'},
{'label':'vocal house','value':'vocal house'},
{'label':'vocal jazz','value':'vocal jazz'},
{'label':'vocal music','value':'vocal music'},
{'label':'volksmusik','value':'volksmusik'},
{'label':'waila','value':'waila'},
{'label':'waltz','value':'waltz'},
{'label':'wangga','value':'wangga'},
{'label':'warabe uta','value':'warabe uta'},
{'label':'wassoulou','value':'wassoulou'},
{'label':'weld','value':'weld'},
{'label':'were music','value':'were music'},
{'label':'west coast hip hop','value':'west coast hip hop'},
{'label':'west coast jazz','value':'west coast jazz'},
{'label':'western','value':'western'},
{'label':'western blues','value':'western blues'},
{'label':'western swing','value':'western swing'},
{'label':'witch house','value':'witch house'},
{'label':'wizard rock','value':'wizard rock'},
{'label':'women\'s music','value':'women\'s music'},
{'label':'wong shadow','value':'wong shadow'},
{'label':'wonky pop','value':'wonky pop'},
{'label':'wood','value':'wood'},
{'label':'work song','value':'work song'},
{'label':'world fusion','value':'world fusion'},
{'label':'world fusion music','value':'world fusion music'},
{'label':'world music','value':'world music'},
{'label':'worldbeat','value':'worldbeat'},
{'label':'xhosa music','value':'xhosa music'},
{'label':'xoomii','value':'xoomii'},
{'label':'yo-pop','value':'yo-pop'},
{'label':'yodeling','value':'yodeling'},
{'label':'yukar','value':'yukar'},
{'label':'yé-yé','value':'yé-yé'},
{'label':'zajal','value':'zajal'},
{'label':'zapin','value':'zapin'},
{'label':'zarzuela','value':'zarzuela'},
{'label':'zeibekiko','value':'zeibekiko'},
{'label':'zeuhl','value':'zeuhl'},
{'label':'ziglibithy','value':'ziglibithy'},
{'label':'zouglou','value':'zouglou'},
{'label':'zouk','value':'zouk'},
{'label':'zouk chouv','value':'zouk chouv'},
{'label':'zouklove','value':'zouklove'},
{'label':'zulu music','value':'zulu music'},
{'label':'zydeco','value':'zydeco'},
]
